# Generated by Django 2.1.1 on 2018-09-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20180930_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulecontinue',
            name='module',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
