# Generated by Django 2.1.1 on 2018-09-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20180930_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulecontinue',
            name='module',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
