# Generated by Django 2.1.1 on 2018-09-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20180930_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulecontinue',
            name='course',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='modulecontinue',
            name='module',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
