# Generated by Django 2.1.1 on 2018-10-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20180930_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulecontinue',
            name='student',
        ),
        migrations.DeleteModel(
            name='ModuleContinue',
        ),
    ]
